name: Manual Release and Publish

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
      release_notes:
        description: 'Release notes (optional - will use latest commit message if empty)'
        required: false
        default: ''

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

    - name: Run pre-build tests
      run: npm test

    - name: Build project
      run: npm run build

    - name: Run post-build tests
      run: npm run test:unit

    - name: Bump version and get new version
      id: version
      run: |
        echo "Current version: $(node -p "require('./package.json').version")"
        echo "Bumping ${{ github.event.inputs.version_type }} version..."
        npm version ${{ github.event.inputs.version_type }} --no-git-tag-version
        NEW_VERSION=$(node -p "require('./package.json').version")
        echo "New version: $NEW_VERSION"
        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

    - name: Prepare release notes
      id: release_notes
      run: |
        if [ -n "${{ github.event.inputs.release_notes }}" ]; then
          RELEASE_NOTES="${{ github.event.inputs.release_notes }}"
        else
          COMMIT_MSG="$(git log -1 --pretty=%B)"
          RELEASE_NOTES=$(echo "$COMMIT_MSG" | sed 's/^[a-z]*: *//' | sed 's/^[A-Z]/\L&/')
        fi
        echo "Release notes: $RELEASE_NOTES"
        {
          echo 'notes<<EOF'
          echo "$RELEASE_NOTES"
          echo EOF
        } >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: "Release v${{ steps.version.outputs.version }}"
        body: ${{ steps.release_notes.outputs.notes }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to npm
      run: |
        echo "Publishing gravixlayer@${{ steps.version.outputs.version }} to NPM..."
        npm publish --access public
        echo "✅ Successfully published to NPM!"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}